name: Mohawk AOT Release
on:
  push:
    tags: ['v*']

jobs:
  build-aot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasi
      - name: Install Wasmtime
        run: curl https://wasmtime.dev/install.sh -sSf | bash && echo "$HOME/.wasmtime/bin" >> $GITHUB_PATH
      
      - name: Build and Pre-compile
        run: |
          cargo build --target wasm32-wasi --release
          wasmtime compile --out mohawk_core.cwasm target/wasm32-wasi/release/mohawk_core.wasm
          sha256sum mohawk_core.cwasm | awk '{print $1}' > golden_hash.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mohawk_core.cwasm
            golden_hash.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
